Create Database e;
CREATE TABLE KhachHang(
  Id INT IDENTITY PRIMARY KEY, HoTen NVARCHAR(100) NOT NULL, NgaySinh DATE,
  CMND VARCHAR(20) UNIQUE, DiaChi NVARCHAR(200), DienThoai VARCHAR(15),
  TenDangNhap VARCHAR(50) NOT NULL UNIQUE, MatKhauHash VARBINARY(64) NOT NULL, Email VARCHAR(100));
CREATE TABLE NhomSanPham(Id INT PRIMARY KEY, Ten NVARCHAR(100) NOT NULL);
CREATE TABLE SanPham( -- bản cache từ HT quản lý SP
  MaSP VARCHAR(20) PRIMARY KEY, NhomId INT REFERENCES NhomSanPham(Id), Ten NVARCHAR(200) NOT NULL,
  NhaSX NVARCHAR(100), MoTa NVARCHAR(MAX), ThongSo NVARCHAR(MAX), Gia DECIMAL(18,0) NOT NULL, ConHang BIT NOT NULL);
CREATE TABLE LoaiPhieu(Id TINYINT PRIMARY KEY, Ten NVARCHAR(50), PhiCoBan DECIMAL(18,0), NgayXuLy TINYINT);
CREATE TABLE LoaiThe(Id TINYINT PRIMARY KEY, Ten VARCHAR(20), SoChuSo TINYINT, SoChuSoCSV TINYINT, LePhi DECIMAL(18,0));
CREATE TABLE DonDatHang(
  Id INT IDENTITY PRIMARY KEY, KhachHangId INT NOT NULL REFERENCES KhachHang(Id),
  LoaiPhieuId TINYINT NOT NULL REFERENCES LoaiPhieu(Id), ThoiDiem DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
  NguoiNhan NVARCHAR(100) NOT NULL, DiaChiNhan NVARCHAR(200) NOT NULL, DienThoaiNhan VARCHAR(15) NOT NULL,
  LoaiTheId TINYINT NOT NULL REFERENCES LoaiThe(Id), TheCuoi4 CHAR(4) NOT NULL, -- KHÔNG lưu số thẻ đầy đủ/CSV
  PhiGiao DECIMAL(18,0) NOT NULL, PhiThe DECIMAL(18,0) NOT NULL, Tong DECIMAL(18,0) NOT NULL,
  TrangThai VARCHAR(20) NOT NULL);
CREATE TABLE ChiTietDon(
  DonId INT REFERENCES DonDatHang(Id), MaSP VARCHAR(20) REFERENCES SanPham(MaSP),
  SoLuong INT NOT NULL CHECK(SoLuong>0), DonGia DECIMAL(18,0) NOT NULL, PRIMARY KEY(DonId, MaSP));